### ISSUE TITLE
将socket.io的服务端启动后，出现xhr poll error

### ISSUE THREAD

**Issue by cdasl** [weapp-socketio/socket.io-weapp-demo#1]
小程序端只是把url换了下

**Comment by cdasl** [comment]
![image](https://user-images.githubusercontent.com/30762866/40657910-126bd150-637c-11e8-9ff4-0982e0419c1d.png)

**Comment by gongzili456** [comment]
请务必注意: 因为 Server 的地址是 HTTPS的, 由于小程序开发版本对域名的限制, 请在微信开发者工具 -> 详情 菜单中勾选 不校验合法域名、web-view（业务域名）、TLS 版本以及 HTTPS 证书

**Comment by cdasl** [comment]
![image](https://user-images.githubusercontent.com/30762866/40657999-544dd0f0-637c-11e8-892a-2eb3e2629dfc.png)

**Comment by gongzili456** [comment]
取消勾选

**Comment by cdasl** [comment]
大佬可否分享一下server 端的代码？

**Comment by gongzili456** [comment]
Server 端使用的是 socket.io 官方的 chat demo 源码, 可以去看看

**Comment by cdasl** [comment]
![image](https://user-images.githubusercontent.com/30762866/40658095-a5199fb4-637c-11e8-8b1c-036506e3da9e.png)

**Comment by cdasl** [comment]
没有任何改动吗？

**Comment by gongzili456** [comment]
没有的，你重新编译刷新一下

**Comment by cdasl** [comment]
依然不行=_=

**Comment by gongzili456** [comment]
你把URL换了？是什么意思？

**Comment by cdasl** [comment]
`
    const socket = (this.socket = io(
      'https://vast-plateau-30681.herokuapp.com/'
    ))`
把这个url换成了我自己的服务器的，上面有socket.io的chat demo

**Comment by gongzili456** [comment]
用我的URL也不行吗？

**Comment by cdasl** [comment]
完全没问题，一换就出错

**Comment by gongzili456** [comment]
检查一下你的 Server或者 nginx配置

**Comment by cdasl** [comment]
把我的https换成http就好了，原因不明

**Comment by wfzong** [comment]
我也有同样的问题，在开发工具里OK，用手机预览就提示：xhr poll error

**Comment by wfzong** [comment]
![_20180619185009](https://user-images.githubusercontent.com/12407298/41593200-ddd8dbb4-73f1-11e8-9fd8-4919cff61bcb.jpg)
直接用的你的URL也不行，求帮助、求提携~

**Comment by gongzili456** [comment]
取消勾选『不校验域名合法性』了吗？

**Comment by gongzili456** [comment]
模拟器需要勾选『不校验域名合法性』

真机需要开启 Debug 模式

**Comment by wfzong** [comment]
开发者工具里，已经勾选 不校验域名合法性，并且可以正常运行。
在手机里“预览”和“远程调试”不行，您说的“真机需要开启 Debug 模式”，具体指的是什么呢？

**Comment by gongzili456** [comment]
![wechatimg1](https://user-images.githubusercontent.com/6082335/41633952-fe6f37b0-7473-11e8-9543-bb8d112473f9.jpeg)

**Comment by wfzong** [comment]
打开调试模式后好了，谢谢。
现在有点担心的是，发布线上会不会有问题，您有没有正式项目有应用过？
