### ISSUE TITLE
无法通过命名空间连接

### ISSUE THREAD

**Issue by gogym** [weapp-socketio/socket.io-weapp-demo#2]
const socket = (this.socket = io(
      'https://vast-plateau-30681.herokuapp.com/news',
       { transports: ['websocket']}))
默认连接没有问题，但如果后面加上命名空间，无法连接。

**Comment by gogym** [comment]
应该是    IP:端口号/命名空间      这种形式不行

**Comment by gongzili456** [comment]
@gogym  请检查自己的 Server 是否监听了命名空间，

请参考：[https://github.com/10cella/weapp.socket.io/issues/22](https://github.com/10cella/weapp.socket.io/issues/22)
